spring:
  datasource:
    password: pass
    username: postgres
    url: jdbc:postgresql://localhost:5432/my_database

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: abcccccccccccccccc
    #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: localhost:9092
#    listener:
#      concurrency: 1
#      poll-timeout: 1000
#    admin:
#      auto-create: true