spring:
  datasource:
    password: pass
    username: postgres
    url: jdbc:postgresql://localhost:5432/my_database

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: abcccccccccccccccc

    bootstrap-servers: localhost:9093

kafka-config:
  request-topic-name: subsystem-request-topic

#    #listener:
#     # concurrency: 1
#     # poll-timeout: 1000
#    #admin:
#     # auto-create: true

shards.kafka.config:
  shard-a:
    topics:
      request-topic: request-topic
      response-topic: response-topic
    properties:
      producer:
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group-id: abcr
        properties:
          spring.json.trusted.packages: "*"
          spring.json.value.default.type: "com.barabanov.dynamically.kafka.listener.Response"
      bootstrap-servers: localhost:29092

  shard-b:
    topics:
      request-topic: request-topic
      response-topic: response-topic
    properties:
      producer:
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group-id: abcd
        properties:
          spring.json.trusted.packages: "*"
      listener:
        concurrency: 3
        poll-timeout: 1000
      bootstrap-servers: localhost:29093