spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: abc

    bootstrap-servers: localhost:9093

kafka-topics:
  request-topic-name: common-request-topic
  response-topic-name: common-response-topic


shard.configs:
  - shard-name: shard-a
    kafka-config:
      request-topic-name: shard-a-request-topic
      response-topic-name: shard-a-response-topic
      properties:
        producer:
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          group-id: abcr
          properties:
            spring.json.trusted.packages: "*"
        bootstrap-servers: localhost:29092
  - shard-name: shard-b
    kafka-config:
      request-topic-name: shard-b-request-topic
      response-topic-name: shard-b-response-topic
      properties:
        producer:
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          group-id: my_group_id_new
          auto-offset-reset: earliest
          max-poll-records: 300
          properties:
            spring.json.trusted.packages: "*"
        listener:
          type: batch
          concurrency: 2
        #        poll-timeout: 1000
        bootstrap-servers: localhost:29093
