spring:
  datasource:
    password: pass
    username: postgres
    url: jdbc:postgresql://localhost:5432/my_database

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: abcccccccccccccccc

    bootstrap-servers: localhost:9092

#    #listener:
#     # concurrency: 1
#     # poll-timeout: 1000
#    #admin:
#     # auto-create: true

kafka.shard.config:
  shard-a:
    kafka-brokers: localhost:9092
    topics-properties:
      request-topic:
        name: request-topic
        concurrency: 1
        poll-timeout: 500
        max-poll-records: 1000
      response-topic:
        name: response-topic
  shard-b:
    kafka-brokers: kafka-url-2
    topics-properties:
      request-topic:
        name: my-request-topic-2
        concurrency: 1
        poll-timeout: 500
        max-poll-records: 1000
      response-topic:
        name: their-response-topic-2